apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eudico-node
  labels:
    app: minerNode
    tier: node
spec:
  serviceName: eudico-node
  replicas: 1
  selector:
    matchLabels:
      app: minernode
      tier: node
  template:
    metadata:
      labels:
        app: minernode
        tier: node
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/debug/metrics"
    spec:
      containers:
        - name: eudico-node
          image: zondax/filecoin-eudico:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 1234
            - containerPort: 1235
            - containerPort: 1236
          volumeMounts:
            - name: eudico-config
              mountPath: /config
      volumes:
        - name: eudico-config
          persistentVolumeClaim:
            claimName: config-pv

